server.port: 8083
spring:
  application.name: tech-services-app
  datasource:
    url: jdbc:postgresql://localhost:5432/tech-services
    username: tech-user
    password: test1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create # create, create-drop, update, validate, none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
